export const resDataList = [
	{
		info: {
			id: "31803",
			name: "McDonald's",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/5/22/97e266e1-4225-4b1a-813a-a9d487acdb53_31803.JPG",
			locality: "Magnet Mall",
			areaName: "Bhandup West",
			costForTwo: "₹400 for two",
			cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
			avgRating: 4.5,
			parentId: "630",
			avgRatingString: "4.5",
			totalRatingsString: "38K+",
			sla: {
				deliveryTime: 23,
				lastMileTravel: 1.7,
				serviceability: "SERVICEABLE",
				slaString: "20-25 mins",
				lastMileTravelString: "1.7 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "247438",
			name: "Domino's Pizza",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/14/d971d2b0-3891-4f46-b708-82e317ed7884_247438.JPG",
			locality: "Bhandup East",
			areaName: "Bhandup West",
			costForTwo: "₹400 for two",
			cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
			avgRating: 4.1,
			parentId: "2456",
			avgRatingString: "4.1",
			totalRatingsString: "3.3K+",
			sla: {
				deliveryTime: 25,
				lastMileTravel: 2.9,
				serviceability: "SERVICEABLE",
				slaString: "20-25 mins",
				lastMileTravelString: "2.9 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "28282",
			name: "Chinese Wok",
			cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
			locality: "Vishal Industries",
			areaName: "Bhandup West",
			costForTwo: "₹250 for two",
			cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
			avgRating: 4.2,
			parentId: "61955",
			avgRatingString: "4.2",
			totalRatingsString: "9.1K+",
			sla: {
				deliveryTime: 46,
				lastMileTravel: 4.1,
				serviceability: "SERVICEABLE",
				slaString: "45-50 mins",
				lastMileTravelString: "4.1 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "578577",
			name: "Bakingo-Cakes & Desserts",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/0cab21cb-a1da-4d2d-a348-4e770fbfe31a_578577.JPG",
			locality: "Powai",
			areaName: "IIT main gate Powai",
			costForTwo: "₹299 for two",
			cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
			avgRating: 4.6,
			parentId: "3818",
			avgRatingString: "4.6",
			totalRatingsString: "2.5K+",
			sla: {
				deliveryTime: 30,
				lastMileTravel: 3,
				serviceability: "SERVICEABLE",
				slaString: "30-35 mins",
				lastMileTravelString: "3.0 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "43732",
			name: "The Belgian Waffle Co.",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/17/5100ccf3-ada3-4465-83f1-fc26eccf8371_43732.JPG",
			locality: "Chandra nagar HSL",
			areaName: "Bhandup West",
			costForTwo: "₹200 for two",
			cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
			avgRating: 4.6,
			veg: true,
			parentId: "2233",
			avgRatingString: "4.6",
			totalRatingsString: "11K+",
			sla: {
				deliveryTime: 38,
				lastMileTravel: 2.8,
				serviceability: "SERVICEABLE",
				slaString: "35-40 mins",
				lastMileTravelString: "2.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "361263",
			name: "Wendy's Burgers",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/11/affbe8f8-562e-48ce-9e72-73fcb742b661_361263.JPG",
			locality: "Gamdevi Road",
			areaName: "Bhandup West",
			costForTwo: "₹400 for two",
			cuisines: ["Burgers", "American", "Fast Food", "Snacks"],
			avgRating: 4.4,
			parentId: "972",
			avgRatingString: "4.4",
			totalRatingsString: "4.4K+",
			sla: {
				deliveryTime: 40,
				lastMileTravel: 4.2,
				serviceability: "SERVICEABLE",
				slaString: "40-45 mins",
				lastMileTravelString: "4.2 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "244882",
			name: "NIC Ice Creams",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/10/d23098f4-4a93-4b16-a7ca-776e5ba8ea80_244882.JPG",
			locality: "New Sanjay Niwas",
			areaName: "Bhandup West",
			costForTwo: "₹120 for two",
			cuisines: ["Ice Cream", "Desserts"],
			avgRating: 4.7,
			veg: true,
			parentId: "6249",
			avgRatingString: "4.7",
			totalRatingsString: "3.8K+",
			sla: {
				deliveryTime: 32,
				lastMileTravel: 3.8,
				serviceability: "SERVICEABLE",
				slaString: "30-35 mins",
				lastMileTravelString: "3.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "691016",
			name: "Kwality Walls Ice Cream and More",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/13/a510db8e-ef0a-48ca-b06d-5a39fe2943df_691016.JPG",
			locality: "Gamdevi Road",
			areaName: "Bhandup",
			costForTwo: "₹200 for two",
			cuisines: ["Ice Cream", "Desserts"],
			avgRating: 4.3,
			veg: true,
			parentId: "582",
			avgRatingString: "4.3",
			totalRatingsString: "204",
			sla: {
				deliveryTime: 33,
				lastMileTravel: 4.2,
				serviceability: "SERVICEABLE",
				slaString: "30-35 mins",
				lastMileTravelString: "4.2 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "197706",
			name: "Bikkgane Biryani",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/15/b416fc21-5ba7-468b-a7f6-a768dc90fe68_197706.jpg",
			locality: "Hanuman Road",
			areaName: "Powai",
			costForTwo: "₹400 for two",
			cuisines: ["Biryani", "Hyderabadi", "Andhra", "South Indian", "North Indian", "Mughlai", "Kebabs"],
			avgRating: 4.3,
			parentId: "5070",
			avgRatingString: "4.3",
			totalRatingsString: "12K+",
			sla: {
				deliveryTime: 35,
				lastMileTravel: 3,
				serviceability: "SERVICEABLE",
				slaString: "35-40 mins",
				lastMileTravelString: "3.0 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "466651",
			name: "EatFit",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/6/dc6d7bf3-97cd-4e73-83fd-aff89b38bd83_466651.jpg",
			locality: "Vikhroli West",
			areaName: "Powai",
			costForTwo: "₹250 for two",
			cuisines: ["Chinese", "Healthy Food", "Tandoor", "Pizzas", "North Indian", "Thalis", "Biryani"],
			avgRating: 4.4,
			parentId: "76139",
			avgRatingString: "4.4",
			totalRatingsString: "2.6K+",
			sla: {
				deliveryTime: 52,
				lastMileTravel: 5.5,
				serviceability: "SERVICEABLE",
				slaString: "50-55 mins",
				lastMileTravelString: "5.5 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "485061",
			name: "The Dessert Heaven - Pastry, Brownie and Cakes",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/7e142ec9-4a23-42b8-ad95-de254f7c75ac_485061.jpg",
			locality: "Park Site",
			areaName: "Near Veer Savarkar Marg",
			costForTwo: "₹200 for two",
			cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
			avgRating: 4.5,
			veg: true,
			parentId: "506176",
			avgRatingString: "4.5",
			totalRatingsString: "497",
			sla: {
				deliveryTime: 46,
				lastMileTravel: 5.5,
				serviceability: "SERVICEABLE",
				slaString: "45-50 mins",
				lastMileTravelString: "5.5 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "27633",
			name: "Gopala's Veg Kitchen",
			cloudinaryImageId: "fcfb467ddbee643eefad3353ba2e9f14",
			locality: "Kanjurmarg West",
			areaName: "Bhandup West",
			costForTwo: "₹350 for two",
			cuisines: ["South Indian", "Biryani", "Chinese", "Desserts"],
			avgRating: 4.5,
			veg: true,
			parentId: "9204",
			avgRatingString: "4.5",
			totalRatingsString: "114K+",
			sla: {
				deliveryTime: 35,
				lastMileTravel: 1.6,
				serviceability: "SERVICEABLE",
				slaString: "35-40 mins",
				lastMileTravelString: "1.6 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "25553",
			name: "Subway",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/12/f4a08ddd-2ae3-44a3-a185-ea281843f45d_25553.jpg",
			locality: "Bhandup West",
			areaName: "Bhandup West",
			costForTwo: "₹350 for two",
			cuisines: ["sandwich", "Salads", "wrap", "Healthy Food"],
			avgRating: 4.5,
			parentId: "2",
			avgRatingString: "4.5",
			totalRatingsString: "18K+",
			sla: {
				deliveryTime: 35,
				lastMileTravel: 3.8,
				serviceability: "SERVICEABLE",
				slaString: "35-40 mins",
				lastMileTravelString: "3.8 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "31477",
			name: "Oven Story Pizza",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/5/29/d759fbf4-9e2b-4555-8f81-7ffbde000efd_31477.jpg",
			locality: "Gamdevi Road",
			areaName: "Bhandup West",
			costForTwo: "₹400 for two",
			cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
			avgRating: 4.3,
			parentId: "3534",
			avgRatingString: "4.3",
			totalRatingsString: "6.4K+",
			sla: {
				deliveryTime: 17,
				lastMileTravel: 4.2,
				serviceability: "SERVICEABLE",
				slaString: "15-20 mins",
				lastMileTravelString: "4.2 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "395337",
			name: "McDonald's Gourmet Burger Collection",
			cloudinaryImageId: "mriaylxzxbrh9tucrg48",
			locality: "Magnet Mall",
			areaName: "Bhandup",
			costForTwo: "₹600 for two",
			cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
			avgRating: 4.8,
			parentId: "10761",
			avgRatingString: "4.8",
			totalRatingsString: "331",
			sla: {
				deliveryTime: 19,
				lastMileTravel: 1.7,
				serviceability: "SERVICEABLE",
				slaString: "15-20 mins",
				lastMileTravelString: "1.7 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "298136",
			name: "Monginis Cake Shop",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/18/b6086ad1-9a11-43d8-82d3-4fc388b52ab8_298136.JPG",
			areaName: "Saraogi Estate",
			costForTwo: "₹300 for two",
			cuisines: ["Cakes & Pastries", "Bakery", "Desserts"],
			avgRating: 4.3,
			parentId: "8190",
			avgRatingString: "4.3",
			totalRatingsString: "531",
			sla: {
				deliveryTime: 17,
				lastMileTravel: 1.7,
				serviceability: "SERVICEABLE",
				slaString: "15-20 mins",
				lastMileTravelString: "1.7 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "390085",
			name: "NH1 Bowls - Highway To North",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/081dd4b7-ea89-4432-b9a8-8e709eb7844c_390085.jpg",
			locality: "Lal Bahadur Shastri Road",
			areaName: "Bhandup",
			costForTwo: "₹250 for two",
			cuisines: ["North Indian", "Punjabi", "Home Food"],
			avgRating: 4.6,
			parentId: "22452",
			avgRatingString: "4.6",
			totalRatingsString: "693",
			sla: {
				deliveryTime: 15,
				lastMileTravel: 2.4,
				serviceability: "SERVICEABLE",
				slaString: "10-20 mins",
				lastMileTravelString: "2.4 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "740383",
			name: "Hola Pasta - Fresh Gourmet Pasta",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/f2d8b46a-499b-4c6a-b4b9-60e4f602486a_740383.JPG",
			locality: "LBS road",
			areaName: "Bhandup West",
			costForTwo: "₹250 for two",
			cuisines: ["Pastas", "Italian", "Desserts", "Beverages"],
			avgRating: 4.4,
			parentId: "418135",
			avgRatingString: "4.4",
			totalRatingsString: "90",
			sla: {
				deliveryTime: 25,
				lastMileTravel: 2.4,
				serviceability: "SERVICEABLE",
				slaString: "20-30 mins",
				lastMileTravelString: "2.4 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "692087",
			name: "BOOM - Sub Style Sandwiches",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/463f52f4-fc67-4df1-b4d9-10f512870663_692087.JPG",
			locality: "LBS road",
			areaName: "Bhandup West",
			costForTwo: "₹250 for two",
			cuisines: ["Snacks", "Indian", "Desserts"],
			avgRating: 4.5,
			parentId: "401169",
			avgRatingString: "4.5",
			totalRatingsString: "233",
			sla: {
				deliveryTime: 25,
				lastMileTravel: 2.4,
				serviceability: "SERVICEABLE",
				slaString: "20-30 mins",
				lastMileTravelString: "2.4 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
	{
		info: {
			id: "391032",
			name: "ZAZA Mughal Biryani",
			cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/9/17/aacd7e9e-757c-4fc2-80fe-4b2e78daed31_391032.jpg",
			locality: "Lal Bahadur Shastri Road",
			areaName: "Bhandup",
			costForTwo: "₹250 for two",
			cuisines: ["Biryani", "North Indian", "Awadhi"],
			avgRating: 4.4,
			parentId: "22473",
			avgRatingString: "4.4",
			totalRatingsString: "551",
			sla: {
				deliveryTime: 25,
				lastMileTravel: 2.4,
				serviceability: "SERVICEABLE",
				slaString: "20-30 mins",
				lastMileTravelString: "2.4 km",
				iconType: "ICON_TYPE_EMPTY",
			},
		},
	},
];
